name: Build and Release Firmware

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'sdkconfig.wifi-gateway-dev'
      - 'sdkconfig.wifi-gateway-dev.old'
  workflow_run:
    workflows: ["Update Internal Dependencies"]
    types:
      - completed

# ignore changes to sdkconfig.wifi-gateway-dev
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Determine version
        id: create_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: 'v'
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          enable_prerelease_mode: true

      - name: Update Firmware Version in Header File
        run: |
          sed -i 's/char \*firmwareVersionWifi = "[0-9.]*"/char \*firmwareVersionWifi = "${{ steps.create_version.outputs.version }}"/' src/main.h

      - name: Setup git credential
        run: |
          git config --global credential.helper store
          echo https://${{ secrets.CICD_KEY }}:x-oauth-basic@github.com > ~/.git-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build PlatformIO Project
        run: pio run

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/wifi-gateway-prod/firmware.bin
          tag_name: v${{ steps.create_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}